frontend:
  - changed-files:
      - any-glob-to-any-file:
          - "*.html"
          - "*.js"
          - "*.css"
          - "public/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"
